### ISSUE TITLE
規劃 User Flow

### ISSUE THREAD

**Issue by chenpion** [MonospaceTW/goodfood_bot#42]
[User flow](https://www.draw.io/?state=%7B%22ids%22:%5B%221kzcVYWuVu_DMsnxeqfKiXrlIKmNJFMuA%22%5D,%22action%22:%22open%22,%22userId%22:%22{userId}%22%7D#G1kzcVYWuVu_DMsnxeqfKiXrlIKmNJFMuA)
1. 登入
2. 餐廳列表
3. 菜單列表
4. 完成訂餐

**Comment by Akira543152** [comment]
<img width="962" alt="2018-07-31 09 34 11" src="https://user-images.githubusercontent.com/23371057/43432366-1647678a-94a5-11e8-9b35-5f9f57b04bbd.png">
