### ISSUE TITLE
0731 pre-meeting 

### ISSUE THREAD

**Issue by iamcxa** [MonospaceTW/goodfood_bot#56]
- review schema/ issue 以確認開發方向
- 預先討論分工

**Comment by horsekitlin** [comment]
依據 User flow

https://drive.google.com/open?id=1kzcVYWuVu_DMsnxeqfKiXrlIKmNJFMuA

DB Schema 會長這樣

https://drive.google.com/file/d/13CzOqnIynkZmvIDDG8fPfpYkxrFv1_-Z/view?usp=sharing

可以編輯

如果有缺少可以討論修改
